/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AssetMap: typeof import('./components/AssetMap.vue')['default']
    AssetPopup: typeof import('./components/AssetPopup.vue')['default']
    AssetSidebar: typeof import('./components/AssetSidebar.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Main: typeof import('./components/Main.vue')['default']
    ProcessingView: typeof import('./components/ProcessingView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/SearchBar.vue')['default']
  }
}
